version: '3'
services:
  shoploc-be:
    image: joehj/glop23-24:backend
    ports:
      - "80:8080"
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=techlab
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data: