name: CI/CD Pipeline

on:
  push:
    branches:
      - main  #prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t backend .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag backend $DOCKER_USERNAME/glop23-24:backend
          docker push $DOCKER_USERNAME/glop23-24:backend
          docker build -t postgres .
          docker tag postgres $DOCKER_USERNAME/glop23-24:postgres
          docker push $DOCKER_USERNAME/glop23-24:postgres


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get -y update
          sudo apt-get -y install docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      

  post-deploy:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for backend to start
        run: |
            max_retries=5  # Set the maximum number of retries here
            for i in $(seq 1 $max_retries); do
              if curl -sSf http://localhost:8080/actuator/health -o /dev/null; then
                echo "Backend started successfully."
                exit 0  # Exit with a success status code
              else
                echo "Waiting for backend to start (Retry $i)..."
                sleep 5
              fi
            done
            echo "Maximum retries exceeded. Backend did not start successfully."
            exit 1  # Exit with a failure status code

      - name: Deployed successfully
        run: echo "Deployment successful."

      - name: Clean up
        run: docker-compose -f docker-compose.yml down
