name: JUnit Test Check

on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Run Unit Tests
        run: